name: usdt_bcv
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.8

dependencies:
  flutter:
    sdk: flutter
  flutter_dotenv: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  go_router: ^17.1.0
  get: ^4.7.3
  http: ^1.6.0
  intl: ^0.20.2
  google_fonts: ^8.0.1

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/logo.png
